// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Web platform is not configured for this Firebase project.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        // For now, use Android config as fallback since iOS is not properly configured
        debugPrint('⚠️  iOS Firebase config not available, using Android config');
        return android;
      case TargetPlatform.macOS:
        debugPrint('⚠️  macOS Firebase config not available, using Android config');
        return android;
      case TargetPlatform.windows:
        debugPrint('⚠️  Windows Firebase config not available, using Android config');
        return android;
      case TargetPlatform.linux:
        throw UnsupportedError('Linux platform is not supported for this Firebase project.');
      default:
        throw UnsupportedError('This platform is not supported for Firebase.');
    }
  }

  // Only Android configuration is valid - other platforms use this as fallback
  static const FirebaseOptions android = FirebaseOptions(apiKey: 'AIzaSyCA2M8NipUBigbplh5CG4RNvSdDjtNWiLY', appId: '1:503163975178:android:002fcd13dc1b9305cdd1f3', messagingSenderId: '503163975178', projectId: 'dominate-ecb5e', storageBucket: 'dominate-ecb5e.firebasestorage.app');
}
